### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by arogl** [sampsyo/beets#1232] opened 2015-01-17 07:30 UTC
With threaded set to yes I get the following error:

plugins: chroma discogs lastgenre mbsync fetchart embedart replaygain duplicates missing info scrub zero fromfilename amazon

```
C:\>beet -v import \\?\F:\Music
user configuration: C:\Users\Andrew\AppData\Roaming\beets\config.yaml
data directory: C:\Users\Andrew\AppData\Roaming\beets
Sending event: pluginload
in init Searching amazon
library database: C:\Users\Andrew\AppData\Roaming\beets\library.db
library directory: F:\Music\
Sending event: library_opened
Sending event: import_begin
Import of the directory:
F:\Music
was interrupted. Resume (Y/n)?
Skipping previously-imported path:
```

Above about 4000 dirs

```
Traceback (most recent call last):
  File "D:\Python27\Scripts\beet-script.py", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "D:\python27\lib\site-packages\beets\ui\__init__.py", line 945, in main
    _raw_main(args)
  File "D:\python27\lib\site-packages\beets\ui\__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "D:\python27\lib\site-packages\beets\ui\commands.py", line 873, in import_func
    import_files(lib, paths, query)
  File "D:\python27\lib\site-packages\beets\ui\commands.py", line 845, in import_files
    session.run()
  File "D:\python27\lib\site-packages\beets\importer.py", line 305, in run
    pl.run_parallel(QUEUE_SIZE)
  File "D:\python27\lib\site-packages\beets\util\pipeline.py", line 299, in run
    out = self.coro.send(msg)
  File "D:\python27\lib\site-packages\beets\util\pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "D:\python27\lib\site-packages\beets\importer.py", line 1212, in user_query
    resolve_duplicates(session, task)
  File "D:\python27\lib\site-packages\beets\importer.py", line 1224, in resolve_duplicates
    session.resolve_duplicate(task, found_duplicates)
  File "D:\python27\lib\site-packages\beets\ui\commands.py", line 781, in resolve_duplicate
    not task.is_album,
  File "D:\python27\lib\site-packages\beets\ui\commands.py", line 439, in summarize_items
    average_bitrate = sum([item.bitrate for item in items]) / len(items)
ZeroDivisionError: integer division or modulo by zero
```

Whn I clean up the log it is difficult to determine which album is causing the error.

Setting threaded to no, I do not get the error. 

I can post/email cleaned up logs if required.

**Comment by sampsyo** [comment] 2015-01-17 21:41
Yes, could you please paste a full log from the import (in a gist, perhaps) if you have it? When you narrow down which album is causing it, can you provide it so we can reproduce the problem?

**Comment by arogl** [comment] 2015-01-17 21:52
Gist for failing run:
https://gist.github.com/arogl/e73041f17302bb28eb2e

Gist for successful single threaded run:
https://gist.github.com/arogl/f636d9570ecd3c7c0c2f

I think the album is Lily & Madeline.

**Comment by sampsyo** [comment] 2015-01-17 21:54
> I think the album is Lily & Madeline.

Can you please test that hypothesis? If it is that album, can you provide a copy so we can reproduce?

**Comment by arogl** [comment] 2015-01-18 00:53
I only say I think is that that is next album that comes up under single threaded mode.

I'll try copying it into my new music and try a threaded import.

**Comment by dprus** [comment] 2015-03-18 19:36
I appear to be hitting the same issue and it's happening pretty consistently in various albums. Here's the exception:

```
/mnt/nas/music/Aerosmith/O, Yeah! Ultimate Aerosmith Hits [2002]/FLAC (30 items)
Tagging:
    Aerosmith - O, Yeah! Ultimate Aerosmith Hits
URL:
    http://musicbrainz.org/release/7fb9d2db-bf96-45bf-b089-496fe2758c20
(Similarity: 100.0%) (2xSACD, 2002, US, Columbia)
SACD 1
SACD 2
This album is already in the library!
Traceback (most recent call last):
  File "/home/richard/.local/bin/beet", line 9, in <module>
    load_entry_point('beets==1.3.10', 'console_scripts', 'beet')()
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 945, in main
    _raw_main(args)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/__init__.py", line 935, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 873, in import_func
    import_files(lib, paths, query)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 845, in import_files
    session.run()
  File "/home/richard/.local/lib/python2.7/site-packages/beets/importer.py", line 305, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 299, in run
    out = self.coro.send(msg)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/util/pipeline.py", line 158, in coro
    task = func(*(args + (task,)))
  File "/home/richard/.local/lib/python2.7/site-packages/beets/importer.py", line 1212, in user_query
    resolve_duplicates(session, task)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/importer.py", line 1224, in resolve_duplicates
    session.resolve_duplicate(task, found_duplicates)
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 781, in resolve_duplicate
    not task.is_album,
  File "/home/richard/.local/lib/python2.7/site-packages/beets/ui/commands.py", line 439, in summarize_items
    average_bitrate = sum([item.bitrate for item in items]) / len(items)
ZeroDivisionError: integer division or modulo by zero
```
Here's my config:
```
library: /mnt/nas/music/.beets/library.db
directory: /mnt/nas/music
plugins: fetchart embedart convert info scrub lastgenre
import:
    move: yes
paths:
    default: $albumartist/$album [$year]/$format/$artist - $track - $title
    singleton: Non-Album/$artist/$format/$artist - $title
    comp: Compilations/$album [$year]/$format/$artist - $track - $title
convert:
#    auto: yes
    dest: /mnt/nas/music
    paths:
        default: $albumartist/$album [$year]/AAC/$artist - $track - $title
        singleton: Non-Album/$artist/AAC/$artist - $title
        comp: Compilations/$album [$year]/AAC/$artist - $track - $title
    never_convert_lossy_files: true
    format: aac
    formats:
        aac:
            command: ffmpeg -i $source -y -codec:a libfdk_aac -vbr 5 $dest
            extension: m4a
        mp3:
            command: ffmpeg -i $source -codec:a libmp3lame -q:a 2 $dest
            extension: mp3
#chroma:
#    auto: no
scrub:
    auto: no
```

**Comment by dprus** [comment] 2015-03-18 19:47
I can also confirm that setting "threading: no" in my config file seems to have resolved this issue.

**Comment by sampsyo** [comment] 2015-03-18 19:48
Well, it's still a mystery where those empty albums came from, but #1358 should at least avoid the crash here.

Interesting about threading. Are you importing multiple versions of the same album in quick succession?

**Comment by dprus** [comment] 2015-03-18 19:49
I do have two copies of the same album in my import (one is FLAC and the other AAC). I need two copies of every album because my car won't play FLAC files (unfortunately) but I definitely don't want to throw away my FLAC files :)

**Comment by sampsyo** [comment] 2015-03-19 01:13
Thanks. I'll see about reproducing.

**Comment by brunal** [comment] 2015-03-19 11:03
The `assert` atop `summarize_items()` definition should be triggered. Therefore the items are removed in another thread, between the start and the end on `summarize_items()` execution. #1358 should indeed prevent it from crashing unless you're really unlucky. The problem is still here though.

**Comment by sampsyo** [comment] 2015-11-20 21:54
This should be fixed by some recent changes surrounding the handling of empty duplicate albums.

**Closed by sampsyo** 2015-11-20 21:54 UTC
Labels: needinfo
