### ISSUE TITLE
[embedart] ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by k-f-** [sampsyo/beets#1241] opened 2015-01-18 22:02 UTC
Testing out beets for the first time before fixing my large music library.
Running it over some local files to see how the different plugins react, etc...

error output here: https://gist.github.com/k-f-/78e5ee77101da1d57257

**Comment by k-f-** [comment] 2015-01-18 22:06
beets config: https://gist.github.com/k-f-/6cb053f622a0bc52f9ce

**Comment by sampsyo** [comment] 2015-01-18 22:34
Thanks for the report. Can you please send along a reproducible test case? I think this may be sensitive to the specific files you're importing, so we will need them to figure out what's going on.

Meanwhile, @Kraymer, any clues about why parsing the ImageMagick output might fail? Perhaps we should catch any unexpected output and log an error.

**Comment by k-f-** [comment] 2015-01-18 23:37
As you requested some files I was testing over that gave errors.
http://kfring.com/downloads/beetsfiles.zip

Not exactly sure why, but disabling fetchart results in no errors.

The command I was running:
beet -v import {FILES} 2>&1 | tee beets.log

**Comment by sampsyo** [comment] 2015-01-19 00:12
Thanks for providing the samples. Unfortunately, I can't reproduce this; using your config, these files imported without incident. I'm guessing this could be due to different versions of ImageMagick.

I'm going to improve the error-handling around the errors that you're seeing. This should (a) let the process continue even when IM output can't be parsed, and (b) maybe give some more insight into the malformed output.

**Comment by sampsyo** [comment] 2015-01-19 00:27
OK, error handling added. Can you try this again with the latest source and see if anything is different? If things still go wrong, can you provide the verbose output from an example?

**Comment by brunal** [comment] 2015-01-19 10:50
The handling seems broken: if you get a ValueError you're logging it and continuing, but `phash_diff` won't be defined! Fix & test cases incoming.

**Comment by sampsyo** [comment] 2015-01-19 18:33
Oops; that was incredibly dumb of me—thanks, @brunal. :sparkles:

**Comment by k-f-** [comment] 2015-01-20 16:24
@sampsyo, just wanted to let you guys know making this change in my config has stopped this error.  Not a fix, but it's a start.

```
embedart:
    compare_threshold:    0  # disabled. previously 80.
```

Also, I'd like to just say that ```beets``` is wonderful, wonderful, wonderful.  I've had a anally retentive music collection for over a decade and probably tried ~10 programs & various scripts/code with surprisingly good results.  However, beets is murdering all previous workflows.

thanks!

**Comment by sampsyo** [comment] 2015-01-20 17:05
Yep, that disables the comparison feature where this issue arose. I'll close this now since we have better error handling.

And awesome! I'm glad beets is working out well for you.

**Closed by sampsyo** 2015-01-20 17:05 UTC
Labels: needinfo

**Comment by k-f-** [comment] 2015-01-20 20:10
I think what was causing it to explode:
`cover.jpg` already existed prior to import.
beets fetchart created `cover.1.jpg` or in some cases `cover.2.jpg` which I then manually deleted.

I'll take a look at the source code, but perhaps it was **user error** and the imagemagick stuff was correctly looking for the beets generated `.jpg`. because it wants to use what the library thinks is the art file.

I had hoped fetchart would not download if `cover.jpg` existed in the album dir.

**Comment by sampsyo** [comment] 2015-01-20 21:52
Aha, that is a reasonable explanation.

You are right that `fetchart` should detect your local file before fetching anything new. Let us know if you find any evidence for why that went wrong.
